work/main/objectos/library/Say.class: main/objectos/library/Say.java
	javac -d work/main main/objectos/library/Say.java
	
work/library.jar: work/main/objectos/library/Say.class
	jar --create --file=work/library.jar -C work/main .